### ISSUE TITLE
switches

### ISSUE THREAD

**Issue by conrad66** [Limych/ha-beward#7]
Тут
https://github.com/Limych/ha-beward/tree/feature/outputs-control
есть возможность прописать switches:
Но как я понял там давно ни чего не обновлялось ( последние обновления 5 months ago )
Текущее же обновление 3 months ago
Можно как то эти две "ветки" одного проекта объединить или обновить до актуального состояния ?

**Comment by bublikOff** [comment]
> Тут
> https://github.com/Limych/ha-beward/tree/feature/outputs-control
> есть возможность прописать switches:
> Но как я понял там давно ни чего не обновлялось ( последние обновления 5 months ago )
> Текущее же обновление 3 months ago
> Можно как то эти две "ветки" одного проекта объединить или обновить до актуального состояния ?
При желании можно создать свой выключатель для подачи сигнала на выход

```
  - platform: template
    switches:
      door_unlock:
        friendly_name: Открыть дверь
        icon_template: mdi:door
        value_template: > 
          {% if is_state('switch.door_unlock','on') %}
            false
          {% endif %}
        turn_on: 
          - service: shell_command.door_unlock
        turn_off: 

````

```
shell_command:
  door_unlock: "/usr/bin/curl 'http://192.168.0.5/cgi-bin/alarmout_cgi?channel=0&Output=0&Status=1' -u user:password -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36' --compressed --insecure"

```
