### ISSUE TITLE
Add door lock button

### ISSUE THREAD

**Issue by diemon24** [Limych/ha-beward#71]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I see only sensors, binary sensors and camera.
conf.yaml: 

```
beward:  
  - host: my_ip_for_DK103M
    username: myuser 
    password: mypassword
    binary_sensors:
      - online
      - motion
      - ding
    sensors:
      - last_activity
      - last_motion
      - last_ding
    cameras:
      - live
      - last_motion
      - last_ding
```

### Describe the solution you'd like

please add button to open door lock

### Describe alternatives you've considered

I can't find alternatives 

### Additional context

<img width="787" alt="image" src="https://github.com/Limych/ha-beward/assets/91910101/d9e0519d-2dfc-4a52-a15b-571d0417c05f">

Integration settings: 
<img width="348" alt="image" src="https://github.com/Limych/ha-beward/assets/91910101/700fe099-c077-4a70-a636-93c50aa1ac65">
